apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudtestingapp-config
data:
  ConnectionStrings__DefaultConnection: "Host=postgres-db;Database=cloudtestingapp;Username=postgres;Password=postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudtestingapp-secrets
type: Opaque
data:
  # Echo -n "postgres" | base64 (on windows: [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("postgres")))
  DB_PASSWORD: cG9zdGdyZXM=
